version: '3'
services:
  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    networks:
      - my-network
    ports:
      - "80:80"

  webgoat:
    image: webgoat/webgoat-8.0
    container_name: webgoat
    networks:
      - my-network
    ports:
      - "8080:8080"

  nessus:
    image: tenable/nessus:latest-ubuntu
    container_name: nessus
    networks:
      - my-network
    ports:
      - "8834:8834"

networks:
  my-network:
    name: my-network
    driver: bridge

